plugins {
    id 'java'
    id 'java-library'
    id "com.vanniktech.maven.publish" version "0.35.0"
    id("com.gradleup.shadow") version "9.3.1"
}

group = 'io.github.matita008'
version = '1.1.1'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.18-R0.1-SNAPSHOT")

    compileOnly("org.projectlombok:lombok:1.18.42")
    annotationProcessor("org.projectlombok:lombok:1.18.42")
    testCompileOnly("org.projectlombok:lombok:1.18.42")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.42")

    implementation 'com.zaxxer:HikariCP:7.0.2'
}

def targetJavaVersion = 17
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    archiveClassifier.set('')

    relocate 'com.zaxxer.hikari', 'com.github.matita008.internal.hikari'
    exclude 'org.slf4j'
    exclude 'org/slf4j/**'
    exclude 'META-INF/MANIFEST.MF'
    exclude 'META-INF/maven/org.slf4j/**'

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

mavenPublishing {
    coordinates(project.group, "base-plugin", project.version)

    pom {
        name = 'Base Plugin'
        description = 'A plugin library for other bukkit plugins'
        url = 'https://github.com/Matita008/basePlugin'
        inceptionYear = '2020'
        licenses {
            license {
                name = 'MIT License'
                url = 'https://opensource.org/licenses/MIT'
            }
        }
        developers {
            developer {
                id = 'Matita008'
                name = 'Matita008'
                url = 'https://github.com/Matita008/'
            }
        }
        scm {
            connection = 'scm:git:git://github.com/Matita008/basePlugin.git'
            developerConnection = 'scm:git:ssh://git@github.com/Matita008/basePlugin.git'
            url = 'https://github.com/Matita008/basePlugin'
        }
    }
}

publishing {
    repositories {
        maven {
            name = "GitHub"
            url = uri("https://maven.pkg.github.com/Matita008/basePlugin")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

tasks.register('publishAll') {
    dependsOn("publishToMavenCentral")
    dependsOn("publishAllPublicationsToGitHubRepository")
}
